<?php

namespace AppBundle\Repository;

/**
 * UselessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UselessRepository extends \Doctrine\ORM\EntityRepository
{
}
